import java.util.*;
import java.lang.*;
import java.io.*;
class MyProgram
{
public static void main(String args[])
{
int n=8000;
if(n>20000)
System.out.println('free trolley suitcase');
else if(n>10000)
System.out.println('free travel bag');
else if(n==5000 & above)
System.out.println('free backpck');
else if(n<5000)
System.out.println('collect money even for cover we give');
 }
}